### ISSUE TITLE
Migrate the codebase to .NET 5.0

### ISSUE THREAD

**Issue by gayashanbc** [asgardeo/asgardeo-dotnet-oidc-sdk#12]
### Description
Starting from .NET 5.0[1] onwards .NET Framework and .NET Core platforms will be merged.
Migrating to .NET 5.0 will allow us to target the SDK to other platforms (i.e. Linux, Mac) as well.

[1] https://devblogs.microsoft.com/dotnet/introducing-net-5/

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
