### ISSUE TITLE
[sample] Introduce a mechanism to bump the version of the Sample app to a development version

### ISSUE THREAD

**Issue by gayashanbc** [asgardeo/asgardeo-dotnet-oidc-sdk#15]
### Description
Introduce a mechanism to bump the version of the Sample app to a development version.
Ex: `1.0.2-SNAPSHOT`
Currently, we are using the AssemblyVersion property which does not version suffixes such as `SNAPSHOT`.

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
