### ISSUE TITLE
[sample] Inconsistency among application authorization details labels

### ISSUE THREAD

**Issue by gayashanbc** [asgardeo/asgardeo-dotnet-oidc-sdk#2]
**Description:**
Authorization details field labels are inconsistent among setup and application UIs.
| Label in Installation Wizard | Label in Configuration UI in startup |
|-----------------|----------------------------------------|
| Authorization Endpoint | Authorize Endpoint | 
| Redirect URI | Callback URL |
| Postlogout Redirect URI | PostLogout | 

**Suggested Labels:**
Type/Improvement

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
