### ISSUE TITLE
Can not get User Info

### ISSUE THREAD

**Issue by luckyboyqh** [asgardeo/asgardeo-dotnet-oidc-sdk#26]
userInfo = authenticationHelper.UserInfo;
After debugging i found that userInfo return null
![image](https://user-images.githubusercontent.com/45187058/184531339-e21ccf91-8c10-4d12-ba02-120bc2a414e6.png)

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
